15 create header component
boudewijnbout/shoesight pull request #32
Opened 2023-05-15 09:45 UTC by Finnvb

2023-05-15 12:23 UTC, boudewijnbout requested changes

2023-05-15 12:23 UTC, boudewijnbout commented on components/header/HamburgerMenuDropdown.js
>    console.log(props);
Remove console.log

2023-05-15 12:23 UTC, boudewijnbout commented on components/header/HamburgerMenuDropdownItem.js
> +    <motion.li initial={animateFrom} animate={animateTo}>
In semantic HTML a list in a list is not allowed

2023-05-15 12:23 UTC, boudewijnbout commented on components/header/HamburgerMenuDropdownItem.js
>        <Link className={classes.linkTitle} href={props.link}>
Change the class name to the name of the prop so this is consistent. Prop name is linkName while the class is called linkTitle.

2023-05-15 12:23 UTC, boudewijnbout commented on components/header/HamburgerMenuNav.js
>  function HamburgerMenuNav() {
Maybe change this to the ES6 method of writing JavaScript. Shauri and I use this also this goes for all your written files:

const HarburgerMenuNav = () => {
   return ()
}

2023-05-15 12:23 UTC, boudewijnbout commented on src/styles/Header.module.css
>  @media (max-width: 40rem) {
Built mobile-first. So start on a small screen and then write media-querys that use (min-width: ...) once your screen becomes bigger

2023-05-15 12:23 UTC, boudewijnbout commented on components/header/HamburgerMenuDropdownItem.js
> +  const animateFrom = { opacity: 0, y: -15 };
Why do you use framer-motion without having a meeting with Shauri and me about it? Framer-motion makes our application bigger and slower on top of that is this animation super simple to do with regular CSS

2023-05-15 12:23 UTC, boudewijnbout commented on components/header/HamburgerMenuNav.js
> +      <motion.ul
Please be consistent in your classNames you use different casing, example: HamburgerMenuNav and linkTitle. Shauri and I use the second style

2023-05-15 12:23 UTC, boudewijnbout commented on components/header/HamburgerMenuNav.js
> +          <HamburgerMenuDropdown name="nieuw">
Maybe change this prop to "title" instead of "name" but this a minor thing

2023-05-15 12:23 UTC, boudewijnbout commented on components/header/HamburgerMenuNav.js
> +          <SocialMediaIcons />
The social media icons don't need to be in the li or nav

2023-05-15 12:23 UTC, boudewijnbout commented on components/header/HamburgerMenuNav.js
>  import HamburgerMenuDropdown from "/components/header/HamburgerMenuDropdown";
Change the naming to HamburgerDropdown. It makes the import name a lot smaller and we all know that a hamburger is menu so the menu word is redundant

2023-05-15 12:23 UTC, boudewijnbout commented on components/header/HamburgerMenuNav.js
>  import SocialMediaIcons from "/components/header/SocialMediaIcons";
Social media icons are used in the footer also. The social media icons are a global component, since its used multiple times in the application

2023-05-15 12:48 UTC, Finnvb commented on components/header/HamburgerMenuDropdownItem.js
> +    <motion.li initial={animateFrom} animate={animateTo}>
You can if you wrap every inner <ul> with an <li>

2023-05-15 13:26 UTC, Finnvb commented
Resolved changes

2023-05-15 14:47 UTC, boudewijnbout requested changes

2023-05-15 14:47 UTC, boudewijnbout commented on components/header/Searchbar.js
> +const Searchbar = () => {
Why is there no prop for a placeholder in the searchbar?

2023-05-15 14:47 UTC, boudewijnbout commented on components/header/HamburgerNav.js
> +      <motion.ul
Please try doing this animation with normal CSS, tip: use transform: translateY and opacity

2023-05-17 11:55 UTC, boudewijnbout approved these changes
Accepted

2023-05-17 11:56 UTC, merged