feat: Made responsive + added related articles
boudewijnbout/shoesight pull request #87
Opened 2023-06-07 19:00 UTC by boudewijnbout

2023-06-07 20:05 UTC, Finnvb commented
lgtm m8

2023-06-08 11:39 UTC, SCNMC requested changes

2023-06-08 11:39 UTC, SCNMC commented on src/styles/pages/nieuwDetail.module.css
> +    margin: 10rem auto 0 auto;
vgm is 10 rem auto voldoende

2023-06-08 11:39 UTC, SCNMC commented on src/styles/pages/nieuwDetail.module.css
> +    font-family: "Poppins", sans-serif;
change to css variable

2023-06-08 11:39 UTC, SCNMC commented on src/styles/pages/nieuwDetail.module.css
> +    font-family: "Cormorant", sans-serif;
change to css variable

2023-06-08 11:39 UTC, SCNMC commented on src/styles/theme.css
>      --font-cormorant: "Cormorant", sans-serif ;
dit hoort onder fonts

2023-06-08 11:39 UTC, SCNMC commented on src/styles/pages/nieuwDetail.module.css
> +        margin: 11.5rem auto 0 auto;
zelfde vgm werkt 11.5 rem auto prima

2023-06-08 11:44 UTC, boudewijnbout commented on src/styles/pages/nieuwDetail.module.css
> +    margin: 10rem auto 0 auto;
Besproken

2023-06-08 11:44 UTC, boudewijnbout commented on src/styles/theme.css
>      --font-cormorant: "Cormorant", sans-serif ;
Changed

2023-06-08 11:44 UTC, boudewijnbout commented on src/styles/pages/nieuwDetail.module.css
> +        margin: 11.5rem auto 0 auto;
Besproken

2023-06-08 11:44 UTC, boudewijnbout commented on src/styles/pages/nieuwDetail.module.css
> +    font-family: "Poppins", sans-serif;
Changed

2023-06-08 11:51 UTC, SCNMC approved these changes
lgtm

2023-06-08 11:52 UTC, merged